export const MESSAGE_LOADING = "MESSAGE_LOADING";
export const MESSAGES_BY_CHAT_ID = "MESSAGES_BY_CHAT_ID";
export const MESSAGE_CREATE = "MESSAGE_CREATE";
export const UPDATE_MESSAGES = "UPDATE_MESSAGES";
