export const USER_LIST = "USER_LIST";
export const USER_EDIT_PROFILE = "USER_EDIT_PROFILE";
export const USER_DELETE = "USER_DELETE";
export const USER_FOLLOW = "USER_FOLLOW";
export const USER_UNFOLLOW = "USER_UNFOLLOW";
export const USER_FIND_PEOPLE = "USER_FIND_PEOPLE";
export const USER_LOADING = "USER_LOADING";
export const USER_DETAILS = "USER_DETAILS";
export const CURRENT_USER_PROFILE_DETAILS =
  "CURRENT_USER_PROFILE_DETAILS";
export const UPDATE_CURRENT_USER_FOLLOWING_FOLLOW =
  "UPDATE_CURRENT_USER_FOLLOWING_FOLLOW";
export const UPDATE_CURRENT_USER_FOLLOWING_UNFOLLOW =
  "UPDATE_CURRENT_USER_FOLLOWING_UNFOLLOW";
